services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "8010:8000"  # Changed from 8000 to 8010
      - "9450:9443"  # Changed from 9443 to 9450
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - internal_network

volumes:
  portainer_data:
    external: true

networks:
  internal_network:
    driver: bridge